apiVersion: v1
kind: Pod
metadata:
  name: test-busybox
  namespace: staging
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "echo 'Pod is running!' && sleep 600"]
