apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: "postgres"
  password: "SecurePass123!"
  url: "postgresql://postgres:SecurePass123!@postgresql-service:5432/ecommerce"
